---
- hosts: all
  sudo: yes
  vars:
    kafka:
      version: 0.8.1.1
      scalaVersion: 2.9.2
      mirror: http://apache.cs.uu.nl
      installDir: /opt
  tasks:

  # Install Oracle JVM
  - name: Java | Ensure the Oracle JVM repository is present
    apt_repository:
      repo: ppa:webupd8team/java
      state: present
  - name: Java | Ensure the Oracle license is accepted
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: Java | Ensure Oracle Java 7 is installed
    apt:
      name: oracle-java7-installer
      state: latest

  # Download Kafka
  - name: Kafka | Ensure Kafka {{kafka.version}} is downloaded
    get_url:
      url: "{{kafka.mirror}}/kafka/{{kafka.version}}/kafka_{{kafka.scalaVersion}}-{{kafka.version}}.tgz"
      dest: "/tmp"
  - name: Kafka | Ensure tar is extracted
    command: tar xzf /tmp/kafka_{{kafka.scalaVersion}}-{{kafka.version}}.tgz chdir="{{kafka.installDir}}"

  # TODO: Configure and start ZooKeeper & Kafka